### PR TITLE
Fix import path for bitcask

### PR DESCRIPTION
**Pull request by prologic**
Project has moved to [git.mills.io/prologic/bitcask](https://git.mills.io/prologic/bitcask).

For details on why see: https://github.com/prologic

Thank you! 🙇

### CODE REVIEW

**Review by aschmahmann — APPROVED** [review]

**Comment by Stebalien** [comment]
So, the _correct_ way to have done this would have been to:

1. Tag a final release.
2. Delete the code.
3. Leave comments explaining why.

Would you please go back and do that? Otherwise, there are cascading failures in all transitive dependencies (assuming they're not using the GOPROXY).

**Comment by prologic** [comment]
> So, the _correct_ way to have done this would have been to:
> 
> 1. Tag a final release.
> 2. Delete the code.
> 3. Leave comments explaining why.
> 
> Would you please go back and do that? Otherwise, there are cascading failures in all transitive dependencies (assuming they're not using the GOPROXY).

It's too late for that.

**Comment by Stebalien** [comment]
> It's too late for that.

Can you not just re-push the old repo? I have a copy if you need it.

**Comment by prologic** [comment]
> > It's too late for that.
> 
> Can you not just re-push the old repo? I have a copy if you need it.

No I'm not going to do that. That defeats the point of migrating off of Github and taking my code with me. If you read my posts on the matter you'll understand why I did this. Hope you understand 🙇‍♂️

**Comment by Stebalien** [comment]
I completely get moving _future_ development off of GitHub (and deleting all existing code in a new commit), but this breaks the builds of every _past_ version of every project that depends on it. That is, every past release of this package, and any package that depends on any of those releases, will now (and forever) fail to build without using Google's GOPROXY.

Now, clearly you don't owe me anything. But I want to make sure you understand that you've essentially pulled a leftpad.

**Comment by prologic** [comment]
> leftpad

I understand where you're coming from. I hope you understand where I'm coming from too! 🤗 I **feel** really strongly about what Microsoft and Github (_well they're the same now_) have done. Not only have they violated several or more license agreements, but they're treated "source code" written by the hard working likes if you and me in our spare time as nothing more than "data that can be scraped". It's disgusting, I don't care what good it does.

My only hope is that this will get challenged in court one day.

I do apologise for the way I did this, but rest assured that I've put up a pull-request for basically anything and everything that _is_ or _was_ using any of my Go libraries, this one included. I realise I kind of did things a bit "ass backwards", but in hindsight I don't regret it, because you know... Handing over "data" to "someone else's server" you "have no control over", etc...

**Comment by prologic** [comment]
Is there a Timeline for this getting merged?

**Comment by hsanjuan** [comment]
All tests fail as the used tag is broken for the new location. Would it be possible to update to a working version of bitcask?

**Comment by prologic** [comment]
Oh I see lemme have a look 😳

**Comment by prologic** [comment]
Screen Shot 2021-08-04 at 18 50 48

But tests pass locally for me:

```#!sh
(⎈ |local:default)
prologic@Jamess-iMac
Wed Aug 04 18:50:17
~/Contributions/bitcask_migration/go-ds-bitcask
 (migrate_bitcask) 0
$ go test .
ok  	github.com/ipfs/go-ds-bitcask	(cached)
```

**Comment by prologic** [comment]
I don't know why the Windows tests fail sorry :/

**Comment by hsanjuan** [comment]
It seems there's also a go fmt issue @prologic

**Comment by prologic** [comment]
I fixed that

**Pull request merged**
